name: Test

on:
  push:
    branches: 
      - main
      - feat**
      - test**
      - docs**
      - ref**
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go clean -testcache && go test ./... -v
